POST http://127.0.0.1:5000/?x=1000&y=2500 HTTP/1.1
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="sam/IMG_6647.jpg"
Content-Type: image/jpeg

sam/IMG_6647.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://127.0.0.1:5000/get_bitmask HTTP/1.1